# Generated by Django 5.0 on 2026-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
