# Generated by Django 5.0 on 2026-02-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('inventory', 'Inventory Manager'), ('seller', 'Seller')], default='inventory', max_length=20),
        ),
    ]
