# Generated by Django 5.0 on 2026-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default="ROOPAN'S", max_length=100, null=True),
        ),
    ]
