# Generated by Django 5.2.7 on 2026-03-04 15:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_revert_to_roopaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default="ROOPAAN'S", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LoyaltyDiscountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable loyalty discount for returning customers')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=5.0, help_text='Discount percentage or fixed amount for returning customers', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_days_between_visits', models.IntegerField(default=0, help_text='Minimum days between visits to qualify for discount (0 = no restriction)', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_days_between_visits', models.IntegerField(default=30, help_text='Maximum days between visits to qualify for discount (0 = no restriction)', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum purchase amount to apply loyalty discount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage type)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyalty Discount Configuration',
                'verbose_name_plural': 'Loyalty Discount Configurations',
            },
        ),
    ]
